### ISSUE TITLE
"Invalid Chunk class"

### ISSUE THREAD

**Issue by imjack** [yescallop/Nukkit#9]
### Issue description
Run server and it will convert to anvil which at a certain file (not sure which it's a large map) it prints the error.

### Steps to reproduce the issue

1. ...
2. ...
3. ...

### OS and versions

* Nukkit Version: your 1.0.0 build (latest commit)
 
* Java Version: 1.8

* Host OS: Win10
* Client Version: 1.0.0

### Crashdump, backtrace or other files
21:38:09 [ERROR] Error while unloading a chunk: cn.nukkit.utils.ChunkException: Invalid Chunk class
21:38:09 [ALERT] cn.nukkit.utils.ChunkException: Invalid Chunk class
        at cn.nukkit.level.format.anvil.Anvil.setChunk(Anvil.java:326)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2541)
        at cn.nukkit.level.Level.unloadChunk(Level.java:2502)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2792)
        at cn.nukkit.level.Level.unloadChunks(Level.java:2770)
        at cn.nukkit.level.Level.doTick(Level.java:740)
        at cn.nukkit.Server.checkTickUpdates(Server.java:922)
        at cn.nukkit.Server.tick(Server.java:997)
        at cn.nukkit.Server.tickProcessor(Server.java:793)
        at cn.nukkit.Server.start(Server.java:772)
        at cn.nukkit.Server.<init>(Server.java:463)
        at cn.nukkit.Nukkit.main(Nukkit.java:65)

**Comment by JackboyPlay** [comment]
Where is the jar download?

**Comment by yescallop** [comment]
@JackboyPlay You should compile it yourself

**Comment by yescallop** [comment]
@imjack Cannot reproduce, what's the original map type?

**Comment by JackboyPlay** [comment]
@yescallop I've tried it before I asked you but I failed the .jar isnt working thats the reason why I'll ask you ^^

**Comment by imjack** [comment]
The map was MCRegion
